config/routes.rb
Rails.application.routes.draw do
  get "welcome/home"
  resources :tests do
    resources :questions, only: [:create, :destroy, :edit, :update]
  end
  resources :users, only: [:new, :show, :create, :edit, :update]
  resource :session, only: [:new, :create, :destroy]

  get("/start_test/:id", to: "completed_tests#show")
  post("/start_test/:id", to: "completed_tests#result")

  get("/", to: "welcome#home", as: :root)

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy

  validates :description, presence: true
  validates :solution_id, presence: true, 
    numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_question, only: [:edit, :update, :destroy]
  before_action :authorize_user!, only: [:destroy, :edit, :update]

  # POST /questions
  def create
    # render json: question_params
    @test = Test.find params[:test_id]
    if !(can? :crud, @test)
      redirect_to test_path(@test), alert: 'Access Denied' and return
    end

    @question = Question.new()
    @question.solution_id = question_params["correct"]
    @question.description = question_params["description"]
    @question.test = @test
    respond_to do |format|
      if @question.save
        @question_id = Question.last.id

        @answer = Answer.new()
        @answer.question_id = @question_id
        @answer.content = question_params["d"]
        @answer.save
        
        @answer = Answer.new()
        @answer.question_id = @question_id
        @answer.content = question_params["c"]
        @answer.save

        @answer = Answer.new()
        @answer.question_id = @question_id
        @answer.content = question_params["b"]
        @answer.save

        @answer = Answer.new()
        @answer.question_id = @question_id
        @answer.content = question_params["a"]
        @answer.save

        format.html { redirect_to test_url(@test), notice: "Question was successfully created" }
      else
        @questions = @test.questions.order(created_at: :asc)
        format.html { render "tests/show" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to test_url(@question.test), notice: "Question was successfully destroyed" }
      format.json { head :no_content }
    end
  end

  # GET /questions/1/edit
  def edit
    # render json: set_question
  end

  # PATCH/PUT /questions/1
  def update
    # render json: question_params
    @question.solution_id = question_params["correct"]
    @question.description = question_params["description"]
    respond_to do |format|
      if @question.update(params.require(:question).permit(:description))
        @answers = @question.answers
        @answers[0].content = question_params["a"]
        @answers[0].save
        @answers[1].content = question_params["b"]
        @answers[1].save
        @answers[2].content = question_params["c"]
        @answers[2].save
        @answers[3].content = question_params["d"]
        @answers[3].save
        format.html { redirect_to @question.test, notice: "Question was successfully updated" }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_question
    @question = Question.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def question_params
    params.require(:question).permit(:description, :a, :b, :c, :d, :correct)
  end

  def authorize_user!
    redirect_to test_path(@question.test), alert: 'Access Denied' unless can? :change, @question
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

<div class="field">
    <%= form.label :a %>
    <%= form.text_field :a %>
    <%= form.label :b %>
    <%= form.text_field :b %>
    <%= form.label :c %>
    <%= form.text_field :c %>
    <%= form.label :d %>
    <%= form.text_field :d %>
    <%= form.label :correct %>
    <%= form.select :correct, [1, 2, 3, 4]%>  </div>

  

  <div class="actions">
    <%= form.submit "Edit Question" %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= form_with(model: @question, url: test_question_url(@question.test,@question), local: true) do |form| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

<div class="field">
    <%= form.label :a, "(1)" %>
    <%= form.text_field :a, :value => @question.answers[0].content %> <br>
    <%= form.label :b, "(2)" %>
    <%= form.text_field :b, :value => @question.answers[1].content %> <br>
    <%= form.label :c, "(3)" %>
    <%= form.text_field :c, :value => @question.answers[2].content %> <br>
    <%= form.label :d, "(4)" %>
    <%= form.text_field :d, :value => @question.answers[3].content %> <br>
    <%= form.label :correct, "Solution:" %>
    <%= form.select :correct, [1, 2, 3, 4], :selected => @question.solution_id %>  </div>

  <div class="actions">
    <%= form.submit "Edit Question" %>
  </div>
<% end %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Solution</th>
      <th>Test</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.description %></td>
        <td><%= question.solution_id %></td>
        <td><%= question.test %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @question.description %>
</p>

<p>
  <strong>Solution:</strong>
  <%= @question.solution_id %>
</p>


<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>