config/routes.rb
Rails.application.routes.draw do
  get "welcome/home"
  resources :tests do
    resources :questions, only: [:create, :destroy, :edit, :update]
  end
  resources :users, only: [:new, :show, :create, :edit, :update]
  resource :session, only: [:new, :create, :destroy]

  get("/start_test/:id", to: "completed_tests#show")
  post("/start_test/:id", to: "completed_tests#result")

  get("/", to: "welcome#home", as: :root)

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Brain Dumpz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
<body>
<header>
<nav class="navbar navbar-expand-sm navbar-dark bg-dark ">
    <a class="navbar-brand" href="/">Brain Dumpz
   <i class="fas fa-brain"></i>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active mx-3">
        <%= link_to("Home", root_path) %>
        </li>
        <li class="nav-item active mx-3">
        <%= link_to("Tests", tests_path) %> </li>
   <% if user_signed_in? %>
          <% if current_user.is_teacher == true %>
          <li class="nav-item active mx-3">
            <%= link_to("New Test", new_test_path) %>
          </li>
          <% end %>
          <span class="mx-3 nav-item ">Hello <a href="/users/<%= current_user.id%>"> <%= current_user.full_name %> </a> </span>
          <%= link_to "Sign Out", session_path, method: :delete, data: {confirm: "Are you sure you want to sign out?"} %>
        <% else %>
          <%= link_to "Sign In", new_session_path, :class => "mx-3" %>
          <%= link_to "Sign Up", new_user_path %>
        <% end %>

      </ul>
    </div>
  </nav>

      <% flash.each do |type, message| %>
        <div class="alert alert-<%=flash_class(type)%> alert-dismissible fade show">
          <%= message %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
<% end %>
  </header>
   <div class="container">
  <%= yield %>
  </div>

</body>
</html>